### ISSUE TITLE
Unimplemented rule for shift_expression: 3

### ISSUE THREAD

**Issue by darkoverlordofdata** [gasman/bonsai-c#8]
Referring to issue #7 (https://github.com/gasman/bonsai-c/issues/), I decided to use the compiler and paste the code into a correctly formatted module. However, I still cannot access the heap due to lack of shift operators. Per the spec (http://asmjs.org/spec/latest/), you need to use shift operators to access the heap, for example:

  var HEAP8 = new stdlib.Int8Array(buffer);
  var HEAP16 = new stdlib.Int16Array(buffer);
  var HEAP32 = new stdlib.Int32Array(buffer);
  var HEAPU8 = new stdlib.Uint8Array(buffer);
  var HEAPU16 = new stdlib.Uint16Array(buffer);
  var HEAPU32 = new stdlib.Uint32Array(buffer);
  var HEAPF32 = new stdlib.Float32Array(buffer);
  var HEAPF64 = new stdlib.Float64Array(buffer);

HEAPF64[p>>3]
HEAPF32[p>>2]
HEAPU16[p>>1]
HEAP8[p>>0]

Without this idiom, FireFox rejects the code declared by a "use asm" pragma, it's part of the detection algorithm.

**Comment by gasman** [comment]
Hi @darkoverlordofdata - thanks for the report! I don't quite follow what you're doing to arrive at this error, though. It sounds like you're writing this code (`HEAPF64[p>>3]` etc) into the C source file, which isn't going to work - this is code that would be generated in response to a heap access such as `some_int_array[p]` (once we actually get round to implementing heap storage!), not code that would be written inside your source file.

Perhaps it would be helpful to share your code, in case I'm misunderstanding something?

**Comment by darkoverlordofdata** [comment]
No I'm just trying to use shift. It's missing and I'm pointing out that it is also required by the asmjs spec.
